### PR TITLE
Log at warn level when overriding behaviors

### PR DESCRIPTION
**Pull request by oriahu**
- This should have been logging the key that was being overridden as well
as being logged at level WARN so its easily searchable in kibana

### CODE REVIEW

**Comment by oriahu** [comment]
> Per our logging standards, I think we don't want to be wishy-washy with the 'warning' level. I'd either keep this `info` or make it `error`, if it's a problem that should be addressed. https://app.getguru.com/card/TbzArLdc/Application-Logging-Guidelines

I agree that we should probably work out the deeper issue of defining what the user can / can't do. I think that when we are loading YAML files we should not allow them to override behaviors. Though if they POST a yaml behavior to the admin /api/v1/ server that should be allowed.

**Comment by oriahu** [comment]
It might make sense to abort / halt openmock in this case. It should be corrected locally

**Comment by vzvzv** [comment]
Being able to override a previously defined behavior is a feature. Using for e.g. the admin API to change a behavior defined in a file, or updating the values in a behavior with an extend.

**Comment by oriahu** [comment]
This happens 3 places:
```go
r.Behaviors[m.Key] = m
```

but one of those places is when we initially read the behaviors:
```go
		if r.Behaviors[m.Key] != nil {
			logrus.WithField("key", m.Key).Errorf("Overriding existing behavior: %s", m.Key)
		}
		r.Behaviors[m.Key] = m
```

I think that the other two places is a valid case of 'extending' / 'patching', (it looks like its overriding, but is really extending/patching) But i think this third case is not valid because this is when files are read from yaml. I agree that overriding through the API is completely valid.

I'm just advocating for printing an error in that one case where we set the mock and override another simply based on a key appearing more than once in the yamls. I think the other cases are _fine and dandy_ ™️  features for overriding / patching

**Comment by vzvzv** [comment]
Behaviors loaded only once, at init (see [Load](https://github.com/checkr/openmock/blob/master/load.go#L23). The admin API actually adds changes to redis, and has [OpenMock reload entirely](https://github.com/checkr/openmock/blob/master/admin.go#L56). The other two occurrences of `r.Behaviors[m.Key] = m` are part of the templated behavior functionality.

**Comment by oriahu** [comment]
I see, I think we should populateTemplates differently from files than the ones populated from
redis.

**Pull request closed without merging**
